name: Linter

on: push

jobs:
  lint:
    name: ShellCheck
    runs-on: ubuntu-latest

    steps:
    - name: Check-out repository
      uses: actions/checkout@v4

    - name: Install ShellCheck
      run: sudo apt-get install shellcheck

    - name: Parse shell-scripts
      run: |
        files=$(find . -type f ! -path '*/\.*' -exec grep -lE '^#!(/usr)?/bin/(ba)?sh' {} +)
        if [ -n "$files" ]; then
          shellcheck -a -S warning $files
        else
          echo "No Bourne (sh) or Bourne Again (bash) scripts found."
        fi
